### ISSUE TITLE
Tags in XML files not working

### ISSUE THREAD

**Issue by wimdeblauwe** [mraible/infoq-mini-book#11]
I have a working Gradle build that generates a PDF from my asciidoc sources. This includes some references to XML files with tags and those are working fine.

I am now trying to migrate my content to use this template, but none of the includes that point to XML files are working. Includes to Java files for example are all fine.

My build is using `org.asciidoctor:asciidoctor-gradle-plugin:1.5.7` while this templates uses `org.asciidoctor:asciidoctor-gradle-plugin:1.5.3`. However, when I downgrade my project, the XML includes with tags keep working.

The path to the XML file itself is certainly correct, because when I replace the `[tags=foo]` with `[]` to display the full file, the HTML export has the full contents of the file. (I use `build.sh` to create the HTML file)

**Comment by mraible** [comment]
I recently tried upgrading all the dependencies in my jhipster-book project (which uses this template) and it broke most things. Therefore, I recommend staying with the versions specified in this template.

**Comment by wimdeblauwe** [comment]
I am staying with the current versions when using the template. What I was stating is that I downgraded the plugin I was using to the version you have in the template. I'll try to reproduce the issue with a small sample.

**Comment by wimdeblauwe** [comment]
Ok, good news. It seems the correct syntax is this:

```
<dependencies>
        <!--tag::web-starter[] -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- end::web-starter[] -->
```

I was using this:
```
<dependencies>
        <!--tag::web-starter[]-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--end::web-starter[]-->
```

Notice how `tag` is directly adjacent to the XML comment start and everything else needs a space. 

I found it in a comment on  https://github.com/asciidoctor/asciidoctor/issues/1072

**Comment by mraible** [comment]
Good to know - thanks for following up with the solution. I'm going to close this issue since it's not really related to this template.
