### ISSUE TITLE
All chapters titles are the book titles in the epub file

### ISSUE THREAD

**Issue by funnygerman** [mraible/infoq-mini-book#15]
Actually the issue is in title. 

After generating epub all chapter titles are the book titles.

**Comment by mraible** [comment]
Thanks for reporting this issue. I'll try to take a look this week.

**Comment by funnygerman** [comment]
Issue is :title: Blabla

Probably the solution would be to use doctitle instead.

But this needs to be proved as a proper solution.

Thank you
