### ISSUE TITLE
Cross reference links not working for html

### ISSUE THREAD

**Issue by funnygerman** [mraible/infoq-mini-book#18]
Cross reference links to included chapters are not working for html.

Just an example.

chapter01.adoc
[#chapter01]
= Chapter 01
...

glossary.adoc
a term <<chapter01#chapter01>>

In the generated index.html the link points to chapter01.html#chapter01, but chapter01.html doesn't exist.

By using just <<chapter01>> everything works for html document, but not for epub anymore.

**Comment by mraible** [comment]
This should be fixed now. Please try again on the master branch.
