### ISSUE TITLE
Add ability to link to downloads

### ISSUE THREAD

**Issue by mraible** [mraible/infoq-mini-book#184]
@Mogztter You sent me a prototype a while back that had a heading at the top that allowed you to link to the artifact downloads (e.g. PDF, EPUB). Do you think it'd be possible to add that to this template? 

I'd be happy to pay for your services to implement this feature.

**Comment by Mogztter** [comment]
Sure!
For reference:
![113290611-2f67ba00-92f2-11eb-9f59-7255a0b0871f](https://user-images.githubusercontent.com/333276/205510336-8b8680e2-c582-4092-ac7f-5eed1acc2526.png)

> I like the idea! However, it'd be nice if it were a configuration option. For someone like InfoQ, they might still want the downloads to still happen from a dedicated page.

Do you still want to add a configuration option?

>  Also, I don't think it's necessary to give an option to download the print PDF since that's only meant for printing a hard-copy book.

Should I remove this option?

**Comment by mraible** [comment]
> Do you still want to add a configuration option?

I think both the PDF and EPUB will (in most cases) link to the same page, wether that's an InfoQ landing page or a GitHub releases page. Maybe this section can just be editable with AsciiDoc like the footer is?

> Should I remove this option?

Yes, please.

**Comment by Mogztter** [comment]
Sorry, I haven't got time to work on it before my vacation.
I will probably work on it early 2023. Happy holidays 🎄 🎅🏻 🎁

**Comment by mraible** [comment]
No worries @Mogztter. I hope you have a wonderful holiday break!

**Comment by Mogztter** [comment]
> Maybe this section can just be editable with AsciiDoc like the footer is?

As far as I know, the footer "This page was built using the Antora default UI..." is part of the UI and cannot be edited with AsciiDoc. It can be overridden by providing a handlebar template ("supplemental_ui" feature).

**Comment by mraible** [comment]
@ggrossetie Can I help move this along in any way?
