### ISSUE TITLE
Switch syntax highlighting to Rouge

### ISSUE THREAD

**Issue by mojavelinux** [mraible/infoq-mini-book#22]
Now that Asciidoctor 2 supports Rouge, and Rouge is already supported by Asciidoctor PDF, I recommend switching to it.

**Comment by mojavelinux** [comment]
This will require switching to AsciidoctorJ 2, since that's what provides Rouge for the HTML conversion. But we could start by switching the PDF build.

**Comment by mraible** [comment]
@mojavelinux I have this HTML block that renders funny after the change.

```
[source,html]
.src/app/search/search.component.html
----
<form>
  <input type="search" name="query" [(ngModel)]="query" (keyup.enter)="search()">
  <button type="button" (click)="search()">Search</button>
</form>
----
```

It's Angular HTML, but the highlights are off.

<img width="991" alt="Screen Shot 2019-10-28 at 4 07 44 PM" src="https://user-images.githubusercontent.com/17892/67721938-60c1b500-f99d-11e9-9051-a0ac294f65ab.png">

Here's what it looks like before switching.

![image](https://user-images.githubusercontent.com/17892/67721990-98306180-f99d-11e9-8e40-3468774f88ff.png)

**Comment by mojavelinux** [comment]
That's an indication the rouge gem is out of date. Support for Angular was fixed in a recent version (specifically 3.7.0). AsciidoctorJ PDF needs to upgrade in the next release (which is due out soon). See https://github.com/asciidoctor/asciidoctorj-pdf/blob/master/build.gradle#L51

**Comment by mraible** [comment]
@mojavelinux I [https://github.com/asciidoctor/asciidoctorj-pdf/pull/28](created a PR) to upgrade the gem. However, I'm not sure that'll fix the problem since the example above is in the rendered HTML, not PDF.

**Comment by mojavelinux** [comment]
You'd need the same upgrade either way.

**Comment by robertpanzer** [comment]
My bad, when upgrading to new versions I only checked for upgrades in the runtime deps, not the development deps. (Not sure I fully understand what a development dependency is)

I am planning to make a release of asciidoctorj this weekend which should include rouge 3.12.0. 
I’ll test how this looks like before doing that release.

**Comment by mojavelinux** [comment]
> Not sure I fully understand what a development dependency is

A development dependency is a test suite dependency.

**Comment by robertpanzer** [comment]
Yes, that was what I was thinking as well.
But it’s also an optional runtime dependency, isn’t it?

Just wanted to say sorry, it’s my bad that I completely skipped the dev dependency section on rubygems.org when checking for upgrades of transitive deps.

**Comment by mojavelinux** [comment]
> But it’s also an optional runtime dependency, isn’t it?

Yes, those that's only suggested by the docs. In other words, the integration only works if the gem is present.

**Comment by mojavelinux** [comment]
Where you should be looking is not on rubygems.org, but rather here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/Gemfile

**Comment by robertpanzer** [comment]
I'll make a release of asciidoctorj-pdf 1.5.0-beta.7.1 that contains an updated version of rouge.
Relying on the current version in asciidoctorj will not be enough since users of asciidoctorj-pdf might still work with asciidoctorj 1.5.x or 1.6.x.

**Comment by mojavelinux** [comment]
I would recommend waiting for 1.5.0.rc.1 (or, if things go sideways, beta.8), which should be out later this week.

**Comment by robertpanzer** [comment]
OK, then I'll wait. I'll create a PR though to update rouge to the latest 3.12.0 also in asciidoctor-pdf and to add chunky_png, which I was also missing as I have just seen.

The pdf output of of the angular snippet will look like this with 3.12.0, I guess this is ok:
<img width="1016" alt="Bildschirmfoto 2019-11-03 um 08 58 00" src="https://user-images.githubusercontent.com/1163662/68082075-60e80780-fe18-11e9-9023-e1dfc6efa5ac.png">

**Comment by robertpanzer** [comment]
> add chunky_png, which I was also missing as I have just seen

If I look at the Gemfile it's not there, so I am not going to add it.
