### ISSUE TITLE
Figure and listing numbers not consistent between formats

### ISSUE THREAD

**Issue by johnsgp** [mraible/infoq-mini-book#29]
When I generate HTML, PDF and EPUB versions, the figure and listing numbers for the EPUB version are not consistent with the other two.

Figure numbers flow through the whole document for HTML and PDF, but are reset at each chapter boundary (restart from `Figure 1`) for EPUB.

Listing numbers are missing for HTML and PDF, but are added for EPUB.  If they are added manually in the adoc files, they are then duplicated in the EPUB.  They are also reset to 1 in the EPUB, resulting in captions like this one at the beginning of chapter 2:

`Listing 1. Listing 2.1 Caption`

The easiest way to see this is to clone [my fork of this repo](https://github.com/johnsgp/infoq-mini-book), setup gem bundler as described in README and run `build.sh`, then review the following three files:

- build/asciidoc/epub3/index.epub
- build/asciidoc/html5/index.html
- build/asciidoc/pdf/index.pdf

**Comment by mraible** [comment]
Thanks for the bug report. I'm not sure how to fix this. I'd suggest updating your dependencies to their latest version. Mentioning @mojavelinux in case he's seen this issue.

**Comment by mojavelinux** [comment]
> Listing numbers are missing for HTML and PDF

To get listing numbers in all formats, you need to define the `listing-caption` attribute. Typically `:listing-caption: Listing`. This is predefined in EPUB.

The way numbering is done is different because the formats are different. In EPUB, chapters are separate documents. In HTML and PDF they are all part of one document. This has always been the way the DocBook toolchain works, and Asciidoctor emulated that behavior.

**Comment by johnsgp** [comment]
Thank you @mraible and @mojavelinux for your answers.  I can see two possible solutions and would appreciate your suggestions on which you prefer and how to implement them:

Solution 1: all captions hard-coded
- for listing numbers, switch off listing-caption on EPUB so that the hard-coded numbering that is already in place in my example is used for all three formats
- for figure numbers, switch off figure-caption for all formats and insert hard-coded captions as I've done for the listings

Solution 2: all captions automated with additional chapter prefix;  _is this possible?_
- for listing numbers, switch on listing-caption on for HTML and PDF, and change the format of the listing-number to chapter.sequence (e.g., 1.1, 1.2, ..., 2.1., 2.2)
- for figure numbers, switch on figure-caption for all formats, and change the format as for listings to include the chapter number (1.1, 1.2, ..., 2.1, 2.2).

**Comment by johnsgp** [comment]
I've put Solution 1 into a branch of the above-mentioned repository called `solution-1`.  It works but the numbering is hard-coded, so it's not ideal.

**Comment by slonopotamus** [comment]
asciidoctor-epub3 doesn't reset figure numbering anymore: https://github.com/asciidoctor/asciidoctor-epub3/issues/178

**Comment by johnsgp** [comment]
> asciidoctor-epub3 doesn't reset figure numbering between chapters since 1.5.0.alpha.14: [asciidoctor/asciidoctor-epub3#178](https://github.com/asciidoctor/asciidoctor-epub3/issues/178)

Thanks for the cross-reference @slonopotamus.  However, my thinking is that although infoq-mini-book is using asciidoctor, it should be consistent in itself and thus override the asciidoctor behaviour as needed.  The inconsistency makes it cumbersome for authors to use, because several formats are delivered to InfoQ for publication.

**Comment by mojavelinux** [comment]
I strongly disagree that you should recommend to authors to override the Asciidoctor behavior by hard coding numbers in captions. That takes away a lot of the value of AsciiDoc. The formatting / presentation should be controlled by the tooling, not the author. If the author is doing it, it not only adds burden and risks inconsistency, but reduces the ability to customize the output as well.

What I would find a reasonable compromise is to override the Asciidoctor behavior in the converter itself. That's consistent with Asciidoctor's design to allow for customization through extensions.

So I'm not saying you need to accept the defaults in Asciidoctor, per se, but that it shouldn't be hard coded in the authored document.

**Comment by johnsgp** [comment]
> I strongly disagree that you should recommend to authors to override the Asciidoctor behavior by hard coding numbers in captions. That takes away a lot of the value of AsciiDoc. The formatting / presentation should be controlled by the tooling, not the author. If the author is doing it, it not only adds burden and risks inconsistency, but reduces the ability to customize the output as well.
> 
> What I would find a reasonable compromise is to override the Asciidoctor behavior in the converter itself. That's consistent with Asciidoctor's design to allow for customization through extensions.
> 
> So I'm not saying you need to accept the defaults in Asciidoctor, per se, but that it shouldn't be hard coded in the authored document.

@mojavelinux I absolutely agree with you.  Hardcoding is awful.  It was just a workaround to point out that was the best I could figure out. I'm still hoping for a better solution.

**Comment by slonopotamus** [comment]
I have reread full issue several times and kinda miss the point.

Initial scope was:

1. EPUB resets numbers between chapters. This is no longer valid since https://github.com/asciidoctor/asciidoctor-epub3/issues/178 was fixed.
2. Listing numbers are missing for HTML and PDF, but are added for EPUB. This can be fixed by either enabling listing numbers in HTML/PDF via `listing-caption` attribute like @mojavelinux [said](https://github.com/mraible/infoq-mini-book/issues/29#issuecomment-592754834). Though I'm not sure why this is declared a thing that needs to be fixed at all.

**Comment by johnsgp** [comment]
> asciidoctor-epub3 doesn't reset figure numbering between chapters since 1.5.0.alpha.14: [asciidoctor/asciidoctor-epub3#178](https://github.com/asciidoctor/asciidoctor-epub3/issues/178)

@slonopotamus My apologies, I completely misunderstood what your reply meant.  I see now that it is the right solution.  I have implemented it in [my fork](https://github.com/johnsgp/infoq-mini-book/commit/6f98d92d0229590cf9082092cef7c7a209acfc7f) and tested that it works on EPUB, HTML and PDF.

@mojavelinux Would you be happy with that change as a pull request or have I missed something?

**Comment by mraible** [comment]
@johnsgp Yes, please send a pull request.
