### ISSUE TITLE
Building & releasing multiple books 

### ISSUE THREAD

**Issue by dsebastien** [mraible/infoq-mini-book#54]
Hi @mraible,

For my current project, I've adapted the GH action pipeline to support building/attaching multiple books to a release.
Would that be of interest to include here?

Here's the gist of it:

* files have a specific prefix instead of a generic `index.adoc` name: `book_<Whatever>.adoc`
* the publish.yml file looks for files whose name starts with `book_`
* once the files are identified, the `<Whatever>` part is extracted and used in the cp command

Here's my current publish.yml file:

```
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build book
        run: npm run setup
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Rename files
        run: |
          find ./build -type f -name "book_*.*" | while read fname; do
            dirname=`dirname "$fname"`
            foldername=`basename "$dirname"`
            filename=`basename "$fname"`
            extension="${filename##*.}"
            # Reference: https://stackoverflow.com/questions/428109/extract-substring-in-bash
            filename_without_extension="${filename%.*}"
            bookname=$(echo $filename_without_extension| cut -d'_' -f 2)
            echo "dirname: ${dirname}"
            echo "foldername: ${foldername}"
            echo "filename: ${filename}"
            echo "extension: ${extension}"
            echo "filename without extension: ${filename_without_extension}"
            echo "bookname: ${bookname}"
            echo "--------------------------"
            echo "Copying and renaming..."
            cp "${dirname}/${filename}" "./build/${{ github.event.repository.name }}-${bookname}-${foldername}-${{ env.RELEASE_VERSION }}.${extension}"
            echo "Done!"
            echo "--------------------------"
          done
          cd ./build/asciidoc/html5
          zip -r ${{ github.event.repository.name }}-html5-${{ env.RELEASE_VERSION }}.zip **
          mv *.zip ../..
          cd ../..
          ls
      - name: Upload release assets
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/{*.pdf,*.epub,*.zip}", "Mindmap.mm"]'
```

**Comment by mraible** [comment]
I would expect most people to have one GitHub repo per book. Are you publishing multiple books from the same repo? If so, why?

**Comment by dsebastien** [comment]
Yes, I guess that it's the most common scenario ;-)

I've decided to create variants of my book (https://dev-concepts.dev) so that readers can pick the version that they prefer. Building these from different repos wouldn't make much sense.

**Comment by mraible** [comment]
Yeah, it's probably best to keep this project as-is. However, if you wanted to create a PR to add this to the README, I'd be OK with that. I could also enable the Wiki feature of this project and you could it there.

When you say "variants", what do you mean? Do some versions have different content? Are you creating it in different languages?

**Comment by dsebastien** [comment]
Okay, I understand. I'll send a PR for the readme, in case someone's interested; no need for a full-blown wiki I guess :)

By variants, I mean that I have different entry points, in which I include different parts of the book, and assemble those together with specific images. But I also plan on translating the book (& variants) into different languages later on.

**Comment by mraible** [comment]
Closing for now. Please reopen if you're still interested.
